services:
  hooked:
    build: .
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.srv/hooked/:/app/
      # - /home/service/myrepo/:/repo/
      # - /home/service/.ssh/config:/home/service/.ssh/config:ro
      # - /home/service/.ssh/id_ed25519-myrepo:/home/service/.ssh/id_ed25519-myrepo:ro
      # - /home/service/.ssh/id_ed25519-myrepodep:/repo/id_ed25519:ro
    expose:
      - 3000
    environment:
      - LOG_FILE_PATH=log/app.log
      - HOOKED_HOST=0.0.0.0
      - HOOKED_PORT=3000
      - BUILD_ENTRY_SCRIPT_PATH=./build.sh
      - GITHUB_WEBHOOK_SECRET=
      - GITHUB_WATCH_PUSH_BRANCH=
      - DISCORD_WEBHOOK_URL=
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token-file /run/secrets/cf_tunnel_token
    secrets:
      - cf_tunnel_token
secrets:
  cf_tunnel_token:
    file: ./.secrets/cf_tunnel_token
