services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - AUTH=1
      - PING=1
      - VERSION=1
      - BUILD=1
      - BUILDER=1
      - COMMIT=1
      - EXEC=1
      - LOGS=1
      - NETWORKS=1
      - VOLUMES=1
      - SERVICES=1
      - TASKS=1
      - POST=1
    expose:
      - 2375
    networks:
      - docker-proxy
  hooked:
    image: ghcr.io/jlhg/hooked:latest
    restart: unless-stopped
    depends_on:
      - docker-socket-proxy
    volumes:
      - ./.srv/hooked/:/app/
      # - /path/to/repo/:/repo/
    expose:
      - 3000
    environment:
      - LOG_FILE_PATH=log/app.log
      - HOOKED_HOST=0.0.0.0
      - HOOKED_PORT=3000
      - BUILD_ENTRY_SCRIPT_PATH=./build.sh
      - GITHUB_WEBHOOK_SECRET=/run/secrets/github_webhook_secret
      - GITHUB_WATCH_PUSH_BRANCH=
      - DISCORD_WEBHOOK_URL=/run/secrets/discord_webhook_url
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
    secrets:
      - github_webhook_secret
      - github_pat
      - discord_webhook_url
    networks:
      - default
      - docker-proxy
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token-file /run/secrets/cf_tunnel_token
    secrets:
      - cf_tunnel_token

networks:
  docker-proxy:

secrets:
  github_webhook_secret:
    file: ./.secrets/github_webhook_secret
  github_pat:
    file: ./.secrets/github_pat
  discord_webhook_url:
    file: ./.secrets/discord_webhook_url
  cf_tunnel_token:
    file: ./.secrets/cf_tunnel_token
